# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQAwGwCa4rxOAYqzhV1EwD7V3q-uiSAr
"""

pip install google-play-scraper

from google_play_scraper import reviews_all

result = reviews_all(
    'com.appsfoundry.scoop',
    lang='id',
    country='id'
)

print(len(result))

from google_play_scraper import reviews
import pandas as pd

result, continuation_token = reviews(
    'com.appsfoundry.scoop',  # Gramedia Digital
    lang='id',
    country='id',
    count=500
)

print("Jumlah Review:", len(result))

for r in result[:5]:
    print(r['score'])
    print(r['content'])
    print("------------------")

data = []

for r in result:
    data.append({
        'Tanggal': r['at'],
        'Rating': r['score'],
        'Review': r['content']
    })

df = pd.DataFrame(data)

print(df.head())

df.to_excel("Review_Gramedia_Digital.xlsx", index=False)

print("Data berhasil disimpan")

def sentiment(rating):
    if rating >= 4:
        return "Positif"
    elif rating == 3:
        return "Netral"
    else:
        return "Negatif"

df["Sentimen"] = df["Rating"].apply(sentiment)

print(df["Sentimen"].value_counts())

keyword_cs = [
    "customer service",
    "cs",
    "live chat",
    "admin",
    "respon",
    "balasan"
]

cs_review = df[
    df['Review'].str.contains(
        '|'.join(keyword_cs),
        case=False,
        na=False
    )
]

print(cs_review[['Rating','Review']])

keyword_fitur = [
    "fitur",
    "menu",
    "premium",
    "langganan",
    "offline"
]

fitur_review = df[
    df['Review'].str.contains(
        '|'.join(keyword_fitur),
        case=False,
        na=False
    )
]

print(fitur_review[['Rating','Review']])

keyword_performa = [
    "lemot",
    "loading",
    "error",
    "crash",
    "bug",
    "lambat"
]

performa_review = df[
    df['Review'].str.contains(
        '|'.join(keyword_performa),
        case=False,
        na=False
    )
]

print(performa_review[['Rating','Review']])

kategori = {
    "Customer Service": len(cs_review),
    "Fitur": len(fitur_review),
    "Performa": len(performa_review)
}

hasil = pd.DataFrame(
    list(kategori.items()),
    columns=["Kategori","Jumlah"]
)

print(hasil)

import matplotlib.pyplot as plt

hasil.plot(
    x="Kategori",
    y="Jumlah",
    kind="bar"
)

plt.title("Frekuensi Keluhan Pengguna")
plt.ylabel("Jumlah Review")
plt.show()

def cobit_domain(text):

    text = str(text).lower()

    if any(k in text for k in ['premium','langganan','informasi']):
        return 'EDM05'

    elif any(k in text for k in ['fitur','pengembangan','menu']):
        return 'APO05'

    elif any(k in text for k in ['error','crash','loading','lemot']):
        return 'BAI04'

    elif any(k in text for k in ['customer service','cs','live chat']):
        return 'DSS01'

    else:
        return 'MEA01'

df['Domain_COBIT'] = df['Review'].apply(cobit_domain)

print(df[['Review','Domain_COBIT']].head())

domain_count = df['Domain_COBIT'].value_counts()

print(domain_count)